{{- if .Values.virtualservice.enabled -}}
{{- $fullName := include "grafana.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $prefixPath := .Values.virtualservice.prefix -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "grafana.name" . }}
    chart: {{ template "grafana.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.virtualservice.labels }}
{{ toYaml .Values.virtualservice.labels | indent 4 }}
{{- end }}
{{- with .Values.virtualservice.annotations }}
annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  hosts:
  {{- range .Values.virtualservice.hosts }}
    - {{ . }}
  {{- end }}
  gateways:
  {{- range .Values.virtualservice.gateways }}
    - {{ . }}
  {{- end }}
  http:
  - match:
      - uri:
          prefix: {{ $prefixPath }}
    route:
      - destination:
          host: {{ $fullName }}
          port:
            number: {{ $servicePort }}
{{- end -}}
